---
pipeline:
  build:
    image: docker
    commands:
      - docker build --tag builder --file ./docker/Dockerfile .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

branches: [master]