---
pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache

  node:
    image: node:fermium
    commands:
      - node -v
      - yarn -v
      - yarn install

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache

  build:
    image: docker
    commands:
      - docker build --tag builder --file ./docker/Dockerfile .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


branches: [master]
